# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('has_someone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('r_type', models.CharField(choices=[('humid', 'Humidity'), ('temp', 'Temperature')], max_length=20)),
                ('value_raw', models.IntegerField()),
                ('value_converted', models.FloatField()),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.BusStop')),
            ],
        ),
    ]
