# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_remove_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stops.Game'),
            preserve_default=False,
        ),
    ]
