# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0004_node_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
    ]
