# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0005_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='move_id',
            field=models.IntegerField(default=0),
        ),
    ]
