# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0006_node_move_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.Player')),
            ],
        ),
    ]
