# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0007_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='current_turn', to='stops.Player'),
            preserve_default=False,
        ),
    ]
