# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0008_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_turn', to='stops.Player'),
        ),
    ]
