# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_auto_20161126_1510'),
        ('stops', '0009_auto_20161126_1657'),
    ]

    operations = [
    ]
